WITH CTE AS (
    select 
    STARTED_AT,
    DATE(TO_TIMESTAMP(STARTED_AT)) as DATE_STARTED_AT,
    DAYNAME(TO_TIMESTAMP(STARTED_AT)) as DAY_NAME,
    case when DAYNAME(TO_TIMESTAMP(STARTED_AT)) in ('Sat', 'Sun') then 'WEEKEND'
    else 'BUSINESSDAY' end as DAY_TYPE,
    MONTHNAME(TO_TIMESTAMP(STARTED_AT)) AS MONTH_NAME,
    CASE WHEN MONTH(TO_TIMESTAMP(STARTED_AT)) IN (11,12,1) THEN 'WINTER'
    WHEN MONTH(TO_TIMESTAMP(STARTED_AT)) IN (2,3,4) THEN 'SPRING'
    WHEN MONTH(TO_TIMESTAMP(STARTED_AT)) IN (5,6,7) THEN 'SUMMER'
    ELSE 'AUTUMN' END AS SEASON
    from {{ source('demo', 'bike') }}
    where STARTED_AT != 'started_at'
   
)

select * from CTE