WITH BIKE AS (
    SELECT DISTINCT
    START_STATION_ID AS STATION_ID,
    START_STATION_NAME AS STATION_NAME,
    START_LATITUDE AS LATITIDE,
    START_LONGITUDE AS LONGITUDE
    FROM {{ source('demo', 'bike') }}
    WHERE RIDE_ID != 'ride_id'
)

select * from BIKE