WITH BIKE AS (
    SELECT DISTINCT
    START_STATION_ID AS STATION_ID,
    START_STATION_NAME AS STATION_NAME,
    START_STATION_LATITUDE AS LATITIDE,
    START_STATION_LONGITUDE AS LONGITUDE
    FROM {{ source('demo', 'bike') }}
)

select * from BIKE