WITH TRIPS AS (
    select 
    RIDE_ID,
    RIDEABLE_TYPE,
    DATE(TO_TIMESTAMP(STARTED_AT)) AS TRIP_DATE,
    START_STATION_ID,
    END_STATION_ID,
    RIDE_TYPE,
    TIMESTAMPDIFF(SECOND, TO_TIMESTAMP(STARTED_AT), TO_TIMESTAMP(ENDED_AT)) AS TRIP_DURATION_SECONDS
    from {{ source('demo', 'bike') }}
    where RIDE_ID != 'ride_id'
    ORDER BY DATE(TO_TIMESTAMP(STARTED_AT))
)

select * from TRIPS